### ISSUE TITLE
Error importing gdx-notifications-desktop-jcommunique

### ISSUE THREAD

**Issue by rafaskb** [spookygames/gdx-notifications#4]
`notifications-desktop-os` didn't work for me, so I tried `gdx-notifications-desktop-jcommunique`, which didn't work at all.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/notification/NotificationManager
	at com.grashers.desktop.DesktopBackendAdapter.<init>(DesktopBackendAdapter.java:17)
	at com.grashers.desktop.GrashersLauncher.main(GrashersLauncher.java:15)
Caused by: java.lang.ClassNotFoundException: com.notification.NotificationManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

DesktopBackendAdapter.java:17:
```java
private NotificationHandler notificationHandler = new DesktopNotificationHandler();
```

Details:
macOS 1.14.4
libGDX 1.9.9
lwjgl3

**Comment by SimonIT** [comment]
It seems that jcommunique is missing in the artifact. @thorthur Can you include them or is adding the information to the Readme a better option?

**Comment by arthurtemple** [comment]
Testing it with the demo project, I had trouble reproducing the exact issue. Gradle build could not find the dependency, then including `jcenter()` to repository definitions made it all work like a charm.
Am i missing something here?

I updated the Readme accordingly anyway.

**Comment by SimonIT** [comment]
Works for me

**Comment by rafaskb** [comment]
Adding `jcenter()` to the list of repositories in Gradle fixed it. Glad to see that step was added to the instructions.
